# Generated by Django 6.0.5 on 2026-06-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
