# Generated by Django 6.0.5 on 2026-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
