# Generated by Django 6.0.5 on 2026-06-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_subject_remove_user_subject_enrollment_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='pages.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
