# Generated by Django 6.0.5 on 2026-06-29 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_announcement_teacher_alter_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
           field=models.ForeignKey(
    default=1,
    on_delete=django.db.models.deletion.CASCADE,
    to='pages.user'
),
            preserve_default=False,
        ),
    ]
