# Generated by Django 6.0.5 on 2026-06-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_lesson_description_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
