# Generated by Django 6.0.5 on 2026-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('drive', 'Google Drive'), ('meet', 'Google Meet'), ('zoom', 'Zoom')], default='youtube', max_length=20),
            preserve_default=False,
        ),
    ]
