# Generated by Django 6.0.5 on 2026-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_lesson_pdf_file_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(default='First Prep', max_length=50),
            preserve_default=False,
        ),
    ]
