# Generated by Django 6.0.5 on 2026-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='level',
            field=models.CharField(default='الصف الاول الاعدادي', max_length=50),
            preserve_default=False,
        ),
    ]
