# Generated by Django 6.0.5 on 2026-07-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_studentresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
