# Generated by Django 6.0.5 on 2026-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_enrollment_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='pages.subject'),
        ),
    ]
