# Generated by Django 6.0.5 on 2026-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_user_subject_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
