from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup_student/' , views.signup_student, name='signup_student'),
    path('index/' ,views.index ,name='index'),
    path('contact_us/' ,views.contact_us ,name='contact_us'),
    path('teacher/' ,views.teacher , name='teacher'),
    path('student/' ,views.student , name='student'),
    path('about/',views.about ,name='about'),
    path('home/',views.home ,name='home'),
    path('fqa/',views.fqa,name='fqa'),
    path('service/',views.service ,name='service'),
    path('signup_teacher/' , views.signup_teacher, name='signup_teacher'),
    path(  'send_message/',  views.send_message,  name='send_message'),
    path('enroll/', views.enroll, name='enroll'),
    path('chat/<int:teacher_id>/', views.chat, name='chat'),
    path( "teacher_chat/<int:student_id>/", views.teacher_chat, name="teacher_chat"),
    path( "load_teacher_messages/<int:student_id>/", views.load_teacher_messages, name="load_teacher_messages" ),
    path( "load_student_messages/<int:teacher_id>/", views.load_student_messages,    name="load_student_messages"),
    path(  "add_announcement/",  views.add_announcement,  name="add_announcement"),
    path( "add_lesson/", views.add_lesson, name="add_lesson"),
    # path("pay/", views.pay, name="pay"),
    path( "upload_payment/",  views.upload_payment,  name="upload_payment"),
    path("admin_login/", views.admin_login, name="admin_login"),
    path("admin_dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path(  "add_test/",  views.add_test,  name="add_test" ),
    path(  "add_question/",  views.add_question,  name="add_question" ),
    path( "block_student/<int:student_id>/", views.block_student, name="block_student" ),
    path( "delete_teacher/<int:teacher_id>/", views.delete_teacher, name="delete_teacher" ),
    path(  "unblock_student/<int:id>/",  views.unblock_student,  name="unblock_student" ),
    path( 'watch/<int:lesson_id>/', views.watch_video, name='watch_video'),
    path( "approve_payment/<int:payment_id>/", views.approve_payment, name="approve_payment"),
    path(  "reject_payment/<int:payment_id>/",  views.reject_payment,  name="reject_payment"),
    path(   "renew_subscription/<int:student_id>/",   views.renew_subscription,   name="renew_subscription"),
    path("lessons/", views.show_lessons, name="show_lessons"),
    path("lessons/delete/<int:lesson_id>/", views.delete_lesson, name="delete_lesson"),
    path(  "lessons/edit/<int:lesson_id>/", views.edit_lesson, name="edit_lesson"),
    path("tests/<int:test_id>/", views.take_test, name="take_test"),
    path("test_results/<int:test_id>/" ,views.test_results ,name="test_results"),
    path( "remove_teacher/<int:teacher_id>/", views.remove_teacher, name="remove_teacher"),
]
